<x-layouts.app title="Dashboard">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-clinic-600">Ringkasan operasional</p><h1 class="mt-2 text-3xl font-bold text-slate-950">Selamat datang, {{ str(auth()->user()->name)->before(' ') }}.</h1><p class="mt-2 text-slate-500">Pantau alur pelayanan tanpa membuka data di luar kewenangan Anda.</p></div><span class="inline-flex min-h-11 items-center gap-2 font-bold text-success"><span class="size-2 rounded-full bg-success"></span>Sistem aktif · WIB</span></div>
    <section class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Antrean aktif',$metrics['queue_waiting'],'list-ordered'],['Encounter aktif',$metrics['active_encounters'],'stethoscope'],['Resep farmasi',$metrics['pharmacy_queue'],'pill'],['Pasien aktif',$metrics['patients'],'users-round']] as [$label,$value,$icon])
            <article class="panel p-5"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-clinic-100 text-clinic-700"><i data-lucide="{{ $icon }}" class="size-5"></i></span><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Hari ini</span></div><p class="mt-5 text-sm font-bold text-slate-500">{{ $label }}</p><p class="mt-1 font-heading text-4xl font-bold text-slate-950">{{ $value }}</p></article>
        @endforeach
    </section>
    <section class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><article class="panel overflow-hidden"><div class="border-b border-slate-100 p-6"><p class="text-sm font-bold uppercase tracking-[0.16em] text-danger">Prioritas keselamatan</p><h2 class="mt-2 text-xl font-bold">Antrean urgent & emergency</h2></div><div class="divide-y divide-slate-100">@forelse($priorityTickets as $ticket)<div class="flex items-center justify-between gap-4 p-5"><div><p class="font-bold">No. {{ $ticket->queue_number }} · {{ $ticket->registration->patient->full_name }}</p><p class="mt-1 text-sm text-slate-500">{{ $ticket->service_type }} · {{ $ticket->status }}</p></div><span class="font-bold uppercase text-danger">{{ $ticket->current_priority }}</span></div>@empty<div class="p-8 text-center text-slate-500">Tidak ada antrean prioritas saat ini.</div>@endforelse</div></article><article class="bg-clinic-800 p-6 text-white"><p class="text-sm font-bold uppercase tracking-[0.16em] text-clinic-200">Prinsip sistem</p><h2 class="mt-3 text-2xl font-bold">Catatan final tidak diedit.</h2><p class="mt-4 leading-7 text-clinic-100">Setiap koreksi dibuat sebagai addendum atau resep koreksi baru agar waktu, penulis, dan isi awal tetap dapat ditelusuri.</p><div class="mt-8 flex items-center gap-3 border-t border-clinic-600 pt-5"><i data-lucide="shield-check" class="size-6"></i><span class="font-bold">Immutable · Audited · Role-aware</span></div></article></section>
</x-layouts.app>
